apiVersion: meta.dev.upbound.io/v2alpha1
kind: Project
metadata:
  name: aws-auto-eks-cluster
spec:
  dependsOn:
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-aws-eks
    version: '>=v2.3.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-aws-iam
    version: '>=v2.3.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-aws-kms
    version: '>=v2.3.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-aws-ec2
    version: '>=v2.3.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-kubernetes
    version: '>=v1.2.0'
  - apiVersion: pkg.crossplane.io/v1
    kind: Provider
    package: xpkg.crossplane.io/crossplane-contrib/provider-helm
    version: '>=v1.0.6'
  - apiVersion: pkg.crossplane.io/v1
    kind: Function
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
    version: '>=v0.6.0'
  description: |
    AutoEKSCluster creates AWS EKS clusters with Auto Mode enabled, including
    IAM roles, KMS encryption, and optional Karpenter NodeClass/NodePool resources.
  license: Apache-2.0
  maintainer: Hops Platform Team <platform@hops.ops.com.ai>
  readme: |
    # aws-auto-eks-cluster

    AWS EKS Auto Mode cluster configuration with:
    - EKS cluster with Auto Mode (compute, networking, storage, load balancing)
    - IAM roles for control plane and nodes with required policies
    - KMS encryption for secrets at rest
    - Kubernetes and Helm ProviderConfigs for in-cluster resources
    - Optional OIDC provider for IRSA (Pod Identity preferred)
    - Optional custom access entries for cluster admins
    - Optional security group ingress rules
    - Optional Karpenter NodeClass and NodePool (enabled by default)
  repository: ghcr.io/hops-ops/aws-auto-eks-cluster
  source: github.com/hops-ops/aws-auto-eks-cluster
